//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lis2_save_editor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("lis2_save_editor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Savegame viewer and edior for Life is Strange 2
        ///and The Awesome Adventures of Captain Spirit.
        ///
        ///Version: {0}.
        /// </summary>
        internal static string AboutMessage {
            get {
                return ResourceManager.GetString("AboutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect value!.
        /// </summary>
        internal static string BadValueMessage {
            get {
                return ResourceManager.GetString("BadValueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The save file could not be loaded due to an error:
        ///
        ///{0}.
        /// </summary>
        internal static string CorruptSaveMessage {
            get {
                return ResourceManager.GetString("CorruptSaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon cs_icon {
            get {
                object obj = ResourceManager.GetObject("cs_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DanielIntIcon {
            get {
                object obj = ResourceManager.GetObject("DanielIntIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved successfully!.
        /// </summary>
        internal static string EditsSuccessfullySavedMessage {
            get {
                return ResourceManager.GetString("EditsSuccessfullySavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON file already exists! Overwrite?.
        /// </summary>
        internal static string ExportOverwriteQuestion {
            get {
                return ResourceManager.GetString("ExportOverwriteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported successfully!.
        /// </summary>
        internal static string ExportSuccessfulMessage {
            get {
                return ResourceManager.GetString("ExportSuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon LIS2_icon {
            get {
                object obj = ResourceManager.GetObject("LIS2_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updates were found!.
        /// </summary>
        internal static string NoUpdatesFoundMessage {
            get {
                return ResourceManager.GetString("NoUpdatesFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a settings file for the game! The editor only supports save files..
        /// </summary>
        internal static string OpenedSettingsFileError {
            get {
                return ResourceManager.GetString("OpenedSettingsFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File header mismatch. This means that the file is corrupted or never was a save file in the first place..
        /// </summary>
        internal static string SaveHeaderMismatchError {
            get {
                return ResourceManager.GetString("SaveHeaderMismatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The save version is unknown to the program. Maybe a new episode was released recently?.
        /// </summary>
        internal static string SaveVersionUnknownError {
            get {
                return ResourceManager.GetString("SaveVersionUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} unsaved edits left! Exit without saving?.
        /// </summary>
        internal static string UnsavedEditsWarningMessage {
            get {
                return ResourceManager.GetString("UnsavedEditsWarningMessage", resourceCulture);
            }
        }
    }
}
